export const attachmentNames = {
  "accu-spot-reflex": "Accu-Spot Reflex",
  "kepler-microflex": "Kepler Microflex",
  "otero-micro-dot": "Otero Micro Dot",
  "jason-armory-2x": "Jason Armory 2x",
  "willis-3x": "Willis 3x",
  suppressor: "Suppressor",
  compensator: "Compensator",
  "ported-compensator": "Ported Compensator",
  "muzzle-brake": "Muzzle Brake",
  "chf-barrel": "CHF Barrel",
  "long-barrel": "Long Barrel",
  "gain-twist-barrel": "Gain-Twist Barrel",
  "reinforced-barrel": "Reinforced Barrel",
  "vertical-foregrip": "Vertical Foregrip",
  "ranger-foregrip": "Ranger Foregrip",
  "precision-foregrip": "Precision Foregrip",
  "marksman-foregrip": "Marksman Foregrip",
  "lightweight-foregrip": "Lightweight Foregrip",
  "flip-mag": "Flip Mag",
  "fast-mag-1": "Fast Mag I",
  "fast-mag-2": "Fast Mag II",
  "extended-mag-1": "Extended Mag I",
  "extended-mag-2": "Extended Mag II",
  "assault-grip": "Assault Grip",
  "commando-grip": "Commando Grip",
  "cqb-grip": "CQB Grip",
  "ergonomic-grip": "Ergonomic Grip",
  "quickdraw-grip": "Quickdraw Grip",
  "light-stock": "Light Stock",
  "infiltrator-stock": "Infiltrator Stock",
  "no-stock": "No Stock",
  "agility-stock": "Agility Stock",
  "balanced-stock": "Balanced Stock",
  "fast-motion-laser": "Fast Motion Laser",
  "steady-aim-laser": "Steady Aim Laser",
  "strelok-laser": "Strelok Laser",
  "tactical-laser": "Tactical Laser",
  "target-laser": "Target Laser",
  fmj: "FMJ",
  overpressured: "Overpressured",
  "rapid-fire": "Rapid Fire",
  "recoil-springs": "Recoil Springs",
};

export const attachmentOptions = {
  Optic: [
    "Accu-Spot Reflex",
    "Kepler Microflex",
    "Otero Micro Dot",
    "Jason Armory 2x",
    "Willis 3x",
  ],
  Muzzle: ["Suppressor", "Compensator", "Ported Compensator", "Muzzle Brake"],
  Barrel: [
    "CHF Barrel",
    "Long Barrel",
    "Gain-Twist Barrel",
    "Reinforced Barrel",
  ],
  Underbarrel: [
    "Vertical Foregrip",
    "Ranger Foregrip",
    "Precision Foregrip",
    "Marksman Foregrip",
    "Lightweight Foregrip",
  ],
  Magazine: [
    "Flip Mag",
    "Fast Mag I",
    "Fast Mag II",
    "Extended Mag I",
    "Extended Mag II",
  ],
  "Rear Grip": [
    "Assault Grip",
    "Commando Grip",
    "CQB Grip",
    "Ergonomic Grip",
    "Quickdraw Grip",
  ],
  Stock: [
    "Light Stock",
    "Infiltrator Stock",
    "No Stock",
    "Agility Stock",
    "Balanced Stock",
  ],
  Laser: [
    "Fast Motion Laser",
    "Steady Aim Laser",
    "Strelok Laser",
    "Tactical Laser",
    "Target Laser",
  ],
  "Fire Mods": ["FMJ", "Overpressured", "Rapid Fire", "Recoil Springs"],
};
